name: deforum-music
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip>=23.0
  - nvidia/label/cuda-12.1.0::cuda-toolkit
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.1
  - ffmpeg
  - pip:
      - gradio
      - httpx
      - pillow
      - numpy==1.26.4
      - scipy==1.14.1
      - librosa==0.10.1
      - soundfile==0.12.1
      - openai-whisper==20231117
      - demucs==4.0.1
      - transformers==4.42.4
      - accelerate==0.33.0
      - nltk==3.9.1
      - spacy==3.7.5
      - matplotlib==3.9.2
      - opencv-python==4.10.0.84
      - boto3==1.35.36
      - azure-storage-blob==12.23.1
      - google-cloud-storage==2.18.2
      - tqdm==4.66.5
      - requests==2.32.3
      - pyyaml==6.0.2
      - python-dotenv==1.0.1
      - rich==13.8.1
